#   conda env create -f env.yml
name: ncbi_datasets
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda
  - ruby
  - rb-bio
  - python=3.7
  - pip
  - zip
  - tar
  - unzip
  - krb5=1.14.2=0
  - libdap4=3.18.3=2
  - libiconv=1.14=4
  